version: "3.1"
services:
  mysqldb:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=product
      - MYSQL_DATABASE=products
    ports:
      - "3306:3306"
    volumes:
      - product_data:/var/lib/mysql

volumes:
  product_data:
